name: "Axe Accessibility Test"
description: "Fetch rule IDs from API and run Axe CLI"
author: "Your Name"
inputs:
  service_id:
    description: "Service ID for fetching rule IDs"
    required: true
  url:
    description: "Target URL to run accessibility tests on"
    required: true
# outputs:
#   axe_output:
#     description: "Output from the Axe CLI command"
#     value: ${{ steps.run-axe.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install Axe CLI
      shell: bash
      run: npm install @axe-core/cli -g

    - name: Check Axe CLI Version
      shell: bash
      run: axe --version

    - name: Install Chrome Driver
      shell: bash
      run: npx browser-driver-manager install chrome

    - name: Grant Execution Permission for Script
      shell: bash
      run: chmod +x $GITHUB_ACTION_PATH/run-axe.sh

    - name: Run Axe
      run: $GITHUB_ACTION_PATH/run-axe.sh
      shell: bash
      env:
        SERVICE_ID: ${{ inputs.service_id }}
        URL: ${{ inputs.url }}
