name: "Axe Accessibility Test"
description: "Fetch rule IDs from API and run Axe CLI"
author: "Your Name"
inputs:
  service_id:
    description: "Service ID for fetching rule IDs"
    required: true
  url:
    description: "Target URL to run accessibility tests on"
    required: true
# outputs:
#   axe_output:
#     description: "Output from the Axe CLI command"
#     value: ${{ steps.run-axe.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install Axe CLI
      shell: bash
      run: npm install @axe-core/cli -g

    - name: Check Axe CLI Version
      shell: bash
      run: axe --version

    # - name: Install axe-core
    #   shell: bash
    #   run: npm install axe-core -g

    - name: Setup chrome
      uses: browser-actions/setup-chrome@v1

    - name: Check Chrome Version
      shell: bash
      run: chrome --version

    # - name: Install Chrome Driver
    #   shell: bash
    #   run: npx browser-driver-manager install chrome

    # - name: Install Chrome
    #   shell: bash
    #   run: |
    #     sudo wget -qO- https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > chrome.deb
    #     sudo apt install -y ./chrome.deb
    #     rm chrome.deb

    # - name: Install ChromeDriver
    #   shell: bash
    #   run: |
    #     sudo wget -qO- https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip > chromedriver.zip
    #     sudo unzip chromedriver.zip
    #     sudo mv chromedriver /usr/local/bin/
    #     sudo chmod +x /usr/local/bin/chromedriver
    #     rm chromedriver.zip

    - name: Grant Execution Permission for Script
      shell: bash
      run: chmod +x $GITHUB_ACTION_PATH/run-axe.sh

    - name: Run Axe
      run: $GITHUB_ACTION_PATH/run-axe.sh
      shell: bash
      env:
        SERVICE_ID: ${{ inputs.service_id }}
        URL: ${{ inputs.url }}
        AXE_SOURCE: $GITHUB_ACTION_PATH/axe.js
